steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/luncher-repo/luncher:${_IMAGE_TAG}',
      '-t', '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/luncher-repo/luncher:latest',
      '.'
    ]

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/luncher-repo/luncher:${_IMAGE_TAG}'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/luncher-repo/luncher:latest'
    ]

images:
  - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/luncher-repo/luncher:${_IMAGE_TAG}'
  - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/luncher-repo/luncher:latest'

substitutions:
  _LOCATION: 'us-central1'
  _IMAGE_TAG: 'latest'

options:
  logging: CLOUD_LOGGING_ONLY
